import type { Metadata } from "next";
import { Inter, Barlow } from "next/font/google"
import "./globals.css";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ['latin']
});
const geistMono = Barlow({
  variable: "--font-geist-mono",
    subsets: ["latin"],
     weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
